### ISSUE TITLE
Anime not downloading

### ISSUE THREAD

**Issue by FieldWolf** [phanirithvij/twist.moe#10]
I am having issues downloading anime using this tool.

Commands performed:
1. ./startp.sh
2. Enter link from any anime: https://twist.moe/a/one-punch-man-2
3. Press enter
4. `Enter link from https://twist.moe/
https://twist.moe/a/one-punch-man-2
Creating one-punch-man-2
making it https://twist.moe/a/one-punch-man-2/1
Fetching info...
https://twist.moe/anime/onepunchmans2/[HorribleSubs] One Punch Man S2 - 01 [1080p].mp4
https://twist.moe/anime/onepunchmans2/[HorribleSubs] One Punch Man S2 - 02 [1080p].mp4
Creating one-punch-man-2/list.txt
copying download.sh to one-punch-man-2
Done
Check the Anime folder
Enjoy
You like this anime?
Me too!!`
5. cd Anime/one-punch-man-2/
6. ./download.sh
7. `yes
Total no of episodes : 2
Enter 'a' for all episodes
start at:
a
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154  100   154    0     0   1855      0 --:--:-- --:--:-- --:--:--  1855
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0    534      0 --:--:-- --:--:-- --:--:--   534
https://twist.moe/anime/onepunchmans2/[HorribleSubs] One Punch Man S2 - 01 [1080p].mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154  100   154    0     0   1524      0 --:--:-- --:--:-- --:--:--  1524
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0    416      0 --:--:-- --:--:-- --:--:-- 27000
https://twist.moe/anime/onepunchmans2/[HorribleSubs] One Punch Man S2 - 02 [1080p].mp4`

I then proceed to try and open the file, but nothing works. At all.

**Comment by phanirithvij** [comment]
Sorry man I just saw this issue.
I fixed it.
There was a problem with how I was handling the download.
Do a `git pull`. And close the issue if it works

**Comment by phanirithvij** [comment]
Closing this as there's no response for about 2 months
