### ISSUE TITLE
Syntax Error at jsonP.py, line 5

### ISSUE THREAD

**Issue by CaptainBasculin** [phanirithvij/twist.moe#11]
self explanatory title

**Comment by phanirithvij** [comment]
I will fix it asap.
I have a problem with my Linux machine.

**Comment by phanirithvij** [comment]
And please tell me what are you using is it a linux or a windows machine?

**Comment by phanirithvij** [comment]
If it's windows and you're using `cmd` then it won't recognize `../` but if you have `cmder` you can type `bash` and navigate to that directory then do a `./startp.sh <anime_url>`

**Comment by phanirithvij** [comment]
This was fixed two months ago.
