### ISSUE TITLE
Installation not working with Python

### ISSUE THREAD

**Issue by Mammutor** [phanirithvij/twist.moe#12]
I cloned your program with "cmder". After that  I opened Python and entered "pip install pycryptodome" but there comes out a syntax error. I dont know how Python works and there is no tutorial how to use or to navigate to the downlaod folder.

**Comment by phanirithvij** [comment]
To install pycryptodome you need to do it from the terminal itself, **not** from the python console.
try doing it from the cmder itself

```shell
pip install pycryptodome
```
or you could try
```shell
python -m pip install pycryptodome
```
or
```shell
python3 -m pip install pycryptodome
```

**Comment by Mammutor** [comment]
![twist moe](https://user-images.githubusercontent.com/44206081/58747837-d702cf80-8470-11e9-8c2b-0078909b40b9.png)
C:\Users\Mammu\Downloads\twist.moe\twist.moe
λ pip install pycryptodome
Der Befehl "pip" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

C:\Users\Mammu\Downloads\twist.moe\twist.moe
λ python -m pip install pycryptodome
Der Befehl "python" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

C:\Users\Mammu\Downloads\twist.moe\twist.moe
λ python3 -m pip install pycryptodome
Der Befehl "python3" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

C:\Users\Mammu\Downloads\twist.moe\twist.moe
λ
Thats not working on cmder

**Comment by phanirithvij** [comment]
Ok it seems like python is not in your path variable.

Now you have two ways to resolve this.

1. Uninstall python from control panel and reinstall it from what you
already downloaded and don't forget to tick the add to Path option when
installing.

2. You can manually add the python path to the system env variables. Go to
search and search for "env" and you can find the Environment variables then
you can go and find Path variable in those and add python path there.

I'll try to link video tutorials tomorrow morning (it's night for me) if
you want me to as I don't have a internet connection right now.

**Comment by Mammutor** [comment]
It worked fine, now I installed pycryptodome. But I dont understand the usage:

C:\Users\Mammu\Downloads\twist.moe\twist.moe
λ ./startp.sh https://twist.moe/a/gintama
Der Befehl "." ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

**Comment by phanirithvij** [comment]
Okay on cmder you can type `bash` first then you can try it again like so

```shell
./startp.sh https://twist.moe/a/gintama
```

**Comment by Mammutor** [comment]
That helped a lot, but my list.txt does not get generated:


C:\Users\Mammu\Downloads\cmder
λ cd ..

C:\Users\Mammu\Downloads
λ cd twist.moe

C:\Users\Mammu\Downloads\twist.moe
λ cd twist.moe

C:\Users\Mammu\Downloads\twist.moe\twist.moe
λ bash
Mammu@DESKTOP-47HLKLT ~/Downloads/twist.moe/twist.moe
λ ./startp.sh https://twist.moe/a/gintama
making it https://twist.moe/a/gintama/1
Fetching info...
../api.sh: line 7: python3: command not found
Creating gintama/list.txt
copying download.sh to gintama
Done
Check the Anime folder
Enjoy
You like this anime?
Me too!!
Mammu@DESKTOP-47HLKLT ~/Downloads/twist.moe/twist.moe
λ cd Anime/gintama
Mammu@DESKTOP-47HLKLT ~/Downloads/twist.moe/twist.moe/Anime/gintama
λ ./download.sh
cat: list.txt: No such file or directory
Total no of episodes : 0
Enter 'a' for all episodes
start at:
1
end at:
5
cat: list.txt: No such file or directory
Mammu@DESKTOP-47HLKLT ~/Downloads/twist.moe/twist.moe/Anime/gintama
λ

**Comment by phanirithvij** [comment]
So python3 is not in your path.
Now you can fix this by:
1. Running `./setup.sh`
2. Then go to `api.sh` and change `python3` to `python`
It should look like this:
```shell
IFS=$'\n'

slug=$1
api_url="https://twist.moe/api/anime/${slug}/sources"

json=$(curl -s "${api_url}" -H 'x-access-token: 1rj2vRtegS8Y60B3w3qNZm5T2Q0TN2NR')
links=$(echo $json | python ../jsonP.py)
for link in $links
do
# echo $link
python ../decrypt.py $link
done
```
You can copy/paste the above code in `api.sh`

This is how it should look:
![Screenshot (12)](https://user-images.githubusercontent.com/29627898/58759799-7bf2da80-854d-11e9-8048-da98ba82e35b.png)

**Comment by Mammutor** [comment]
Mammu@DESKTOP-47HLKLT ~/Downloads/twist.moe/twist.moe
λ ./setup.sh
Python is installed
Python 3 is not installed
Crypto, hashlib for python installed
Mammu@DESKTOP-47HLKLT ~/Downloads/twist.moe/twist.moe
λ ./startp.sh https://twist.moe/a/gintama
making it https://twist.moe/a/gintama/1
Fetching info...
C:\Users\Mammu\AppData\Local\Programs\Python\Python37-32\python.exe: can't open file '../jsonP.py': [Errno 2] No such file or directory
Creating gintama/list.txt
copying download.sh to gintama
Done
Check the Anime folder
Enjoy
You like this anime?
Me too!!
Mammu@DESKTOP-47HLKLT ~/Downloads/twist.moe/twist.moe
λ cd Anime/gintama
Mammu@DESKTOP-47HLKLT ~/Downloads/twist.moe/twist.moe/Anime/gintama
λ ./download.sh
cat: list.txt: No such file or directory
Total no of episodes : 0
Enter 'a' for all episodes
start at:
1
end at:
5
cat: list.txt: No such file or directory
Mammu@DESKTOP-47HLKLT ~/Downloads/twist.moe/twist.moe/Anime/gintama
λ

Its not working :(

But I think the problem is that I have a missing file (jsonP.py and setup.py)

**Comment by Mammutor** [comment]
Creating gintama/list.txt
copying download.sh to gintama
Done
Check the Anime folder
Enjoy
You like this anime?
Me too!!
Mammu@DESKTOP-47HLKLT ~/Downloads/twist.moe/twist.moe
λ cd Anime/gintama
Mammu@DESKTOP-47HLKLT ~/Downloads/twist.moe/twist.moe/Anime/gintama
λ ./download.sh
Total no of episodes : 367
Enter 'a' for all episodes
start at:
1
end at:
3
./download.sh: line 31: wget: command not found
./download.sh: line 31: wget: command not found
./download.sh: line 31: wget: command not found

My thinking was right that I do not have the files, but now there is a new problem.

**Comment by phanirithvij** [comment]
Okay, you don't have wget or curl

Try this answer from a SuperUser post

https://superuser.com/a/134687

**Comment by phanirithvij** [comment]
I'm sorry you're facing this many issues.
But please note that this will improve the project a lot and will also help future users.
Thanks for sharing me this instead of simply deleting it and using something else.
I really appreciate it.

**Comment by Mammutor** [comment]
Mammu@DESKTOP-47HLKLT ~/Downloads/twist.moe/twist.moe
λ cd Anime/gintama
Mammu@DESKTOP-47HLKLT ~/Downloads/twist.moe/twist.moe/Anime/gintama
λ ./download.sh
curl is installed yes
Total no of episodes : 367
Enter 'a' for all episodes
start at:
1
end at:
3
curl: (3) [globbing] bad range in column 34
curl: (3) [globbing] bad range in column 34
curl: (3) [globbing] bad range in column 34
Mammu@DESKTOP-47HLKLT ~/Downloads/twist.moe/twist.moe/Anime/gintama
λ

curl is now installed but there is an issue

And its no problem for me. Its GitHub, I do not expect perfect programs.

**Comment by SkrillzPlayz** [comment]
Hello, I'm having this issue and don't know how to solve

$ ./download.sh
curl is installed: yes
cat: list.txt: No such file or directory
Total no of episodes : 0
Enter 'a' for all episodes
start at:
9
end at:
24
**cat: list.txt: No such file or directory**

there is no "list.txt" but there is a "list.sh" in the folder

**Comment by phanirithvij** [comment]
You should go inside `Anime/anime_name/` then use `./download.sh`.

Doing `./download.sh` in `twist.moe/` will not download the anime.

**Comment by phanirithvij** [comment]
And please go a `git pull` before using this as I've updated the code.

**Comment by phanirithvij** [comment]
@SkrillzPlayz were you able to resolve it?

**Comment by SkrillzPlayz** [comment]
I gave up 5 days ago......

**Comment by phanirithvij** [comment]
Well, I posted a solution if you'd like to use it again.
