### ISSUE TITLE
Can't use setup command to run Python

### ISSUE THREAD

**Issue by Drownney** [phanirithvij/twist.moe#14]
I was able to install pycryptodome, but when I type ./setup.sh to install Python, cmder does not recognize it as a command or anything.
![Picture1](https://user-images.githubusercontent.com/53056470/61478793-50db1380-a960-11e9-93b2-e582604bc71c.png)

**Comment by Drownney** [comment]
Quick update:
I was able to clone anime twist but I can't still run ./setup.sh
![Picture1](https://user-images.githubusercontent.com/53056470/61486787-445fb680-a972-11e9-9c2b-465a747d9f07.png)

**Comment by phanirithvij** [comment]
You need to open bash in cmder.
You can first type `bash` then try setup.sh

**Comment by phanirithvij** [comment]
This is how it would look
![usage](https://user-images.githubusercontent.com/29627898/61578109-2b403c80-ab0f-11e9-9db3-aab05afd56e0.png)

**Comment by phanirithvij** [comment]
Were you able to do it?
