### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by nhx26** [phanirithvij/twist.moe#15]
Whenever I run ./startp.sh <anime link> I get a UnicodeDecodeError.
list.txt is not generated in the anime folder

EDIT: Changing the AES key in decrypt.py fixes this.
New key is "LXgIVP&PorO68Rq7dTx8N^lP!Fa5sGJ^*XK"

![image](https://user-images.githubusercontent.com/19762130/62011222-60d7cc00-b186-11e9-94b3-06debd992226.png)

**Comment by nhx26** [comment]
Ok, so it seems that the AES key has changed...
I changed it to '"XgIVP&PorO68Rq7dTx8N^lP!Fa5sGJ^*XK" in decrypt.py and it worked fine.

**Comment by phanirithvij** [comment]
Thanks for informing me. I'll update it.
