### ISSUE TITLE
Non-portable IFs used in dl.sh

### ISSUE THREAD

**Issue by Karkoon** [phanirithvij/twist.moe#19]
Hi. 

The IF statements use a non-portable way of checking conditions. I'm not sure but I think that double brackets don't work for sh but it also didn't work for me, even though I use zsh. 

I think it's because there wasn't a shebang at the start of the file and it must have fallen back to the POSIX standard and failed to execute the script.

So, after adding  

    #!/bin/bash

to dl.sh it worked normally. 

(I also tested #!/bin/zsh but I think bash is more popular and it still works so it can be done like that.) 

I'm not sure about other files, haven't used them yet.

**Comment by phanirithvij** [comment]
Oh, I see. You can send a PR if you like to or I can fix it.

**Comment by phanirithvij** [comment]
made them all `#!/bin/bash`.
