### ISSUE TITLE
list.txt is not getting generated.

### ISSUE THREAD

**Issue by ghost** [phanirithvij/twist.moe#20]
This seems to be a big issue, why?

**Comment by ghost** [comment]
Also many people have this problem.

**Comment by phanirithvij** [comment]
Thanks for reporting. I'll try and reproduce it and if I'm able to reproduce it I'll fix it.

**Comment by phanirithvij** [comment]
Btw paste the output of `./setup.sh` and `./startp.sh`

**Comment by KoroFX** [comment]
what

**Comment by KoroFX** [comment]
Ima do that later , Enjoy the Holidays.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/46395233/71391888-4fe09900-2606-11ea-98b4-ca302499abba.png)
![image](https://user-images.githubusercontent.com/46395233/71391917-6dadfe00-2606-11ea-9bee-b4f03c4e4166.png)

**Comment by ghost** [comment]
and download.sh prints this
![image](https://user-images.githubusercontent.com/46395233/71391982-b5348a00-2606-11ea-99d2-af7a05186e26.png)

**Comment by ghost** [comment]
Btw #21 is meant to be as an Python executable file.

**Comment by ghost** [comment]
Hey i fixed it by installing it to my second drive.
![image](https://user-images.githubusercontent.com/46395233/71392419-38a2ab00-2608-11ea-85fa-0112ed0682f4.png)
Maybe cuz it was installing into the system32 folder and had not the rights to write n stuff.

**Comment by phanirithvij** [comment]
It is working for me. The `list.txt` is getting generated, and the download is successful as well.
You must've forgot to run `setup.sh`.

**Comment by phanirithvij** [comment]
I just noticed I had the same error on windows. I will try and fix it

**Comment by ghost** [comment]
As i sayd you need to install this in another dir like documents/ or in my Case Z:\Twist Downloader

**Comment by ghost** [comment]
If its directly in system32 (default / path git dir) its restricted by Windows and its hard to reach when finished the download.

**Comment by ghost** [comment]
that fixed it for me.
![image](https://user-images.githubusercontent.com/46395233/71393553-57577080-260d-11ea-9ad3-f36e1492fad6.png)

**Comment by ghost** [comment]
I close this, just put a warning for windows users to install this into an seperate folder with:
cd C:/foldername
git clone https://github.com/phanirithvij/twist.moe.git

**Comment by ghost** [comment]
I made an new error as the Downloader doesnt get the Filename only the episode as "-Number" as show above.
