### ISSUE TITLE
Make this an usable Program

### ISSUE THREAD

**Issue by ghost** [phanirithvij/twist.moe#21]
pls

**Comment by phanirithvij** [comment]
What do you mean by making this a usable program?
Please reopen this and explain briefly.
Or If you're talking about making it work again because of issue #20 as I said I'll try and fix it.

**Comment by ghost** [comment]
No i meant as an .exe file

**Comment by phanirithvij** [comment]
I'll try to do it later.

**Comment by KoroFX** [comment]
in the meanwhile i wrote this batchfile to start the downloader in a more lazy way :D
-
@echo off
cd "Twist Downloader/Crunching Things"
start /wait startp.sh
set /p var=Anime Url Name
cd "Anime/%var%"
start download.sh
quit

**Comment by ghost** [comment]
But enjoy the Christmas Days and dont work to much on this in the Holidays.

**Comment by phanirithvij** [comment]
Please don't close this. I'll forget about it.

**Comment by ghost** [comment]
Well ok then,you said you want to rewrite it in phyton and now you think you forget about it xD

**Comment by phanirithvij** [comment]
@KoroFX I'd like you to test it on windows and report any issues if possible https://github.com/phanirithvij/twist.moe/releases/tag/v0.1.3

**Comment by ghost** [comment]
Sure mate will do when im back home.
Thanks for your effort inadvance.

**Comment by ghost** [comment]
Hmm weird, you made a twist file and a twist.exe file.
i downloaded both just in case and executed the exe file.
-
That happend and the Folder got Created but instead of starting downloading it just does nothing.
![image](https://user-images.githubusercontent.com/46395233/71551578-af65ec80-29ea-11ea-94e4-e30e77fa968e.png)

**Comment by KoroFX** [comment]
Im now installing dart and will execute the command you provided and will test then.
(dart2native lib/main.dart -o bin/twist)

**Comment by KoroFX** [comment]
![image](https://user-images.githubusercontent.com/46395233/71551605-66626800-29eb-11ea-8d40-9a63c0bf13c8.png)
ehrm, i suppose dart2native is to make a dart script an executable and that command is not meant for us xd

**Comment by phanirithvij** [comment]
I've still not implemented the downloading part. Just wanted to know before
doing it whether this dart executable would work on other systems. And the
downloading part right now uses wget or curl which are meant for those kind
of things. I'll see what I can do to implement it.

**Comment by phanirithvij** [comment]
As of now, there are two things required, `download.sh` and `twist.exe`.
It is flexible to fetch links and download later because of this.
You are requesting a single executable.
I'm going to implement something like:

```shell
twist.exe <anime_url> # this will only fetch the links
twist.exe <anime_url> --dl(-d) --start(-s) number --end(-e) number # to fecth the links and download from start to end.
twist.exe -i path/to/links.txt --dl(-d) --start(-s) number --end(-e) number # to download whatever is in that file from start to end
twist.exe -i path/to/links.txt --dl(-d) --start(-s) number --count(-c) number # to download count number of episodes from start
```

> Note: There would be no prompts for start, end, etc.. except `Enter the link from twist.moe` in this new model.

But I don't like using it like this. So I'm still going to let the `download.sh` stay.
I will implement it today and push a new release.

@KoroFX how would you like to access the script, would you like to suggest another notation?

**Comment by ghost** [comment]
Entering the url and automatically get ask which episodes to you want, then start downloading.

**Comment by ghost** [comment]
No step inbetween or --dl --start solution.
Entering url get ask which episodes and start.

**Comment by ghost** [comment]
So yeah a single executable but without the -- stuff.

**Comment by phanirithvij** [comment]
If you use frequently, the prompts will become annoying. And the code also
becomes ugly. But don't worry I'll implement it.

**Comment by ghost** [comment]
ill wait for your post here when you implemented the download feature, until then your og tool will be okay. @phanirithvij

**Comment by ghost** [comment]
@phanirithvij when do you implement the download feature into the dart exe ?
