### ISSUE TITLE
Episode Names Wrong/Missing

### ISSUE THREAD

**Issue by ghost** [phanirithvij/twist.moe#22]
Either its Twist.Moe-00 or only -00 ....
![image](https://user-images.githubusercontent.com/46395233/71393758-612da380-260e-11ea-8199-8b7875e66236.png)
![image](https://user-images.githubusercontent.com/46395233/71393768-6854b180-260e-11ea-81d9-050a90ab1bbd.png)

**Comment by phanirithvij** [comment]
This will be fixed by completely taking bash out of the picture. And re writing this in python or dart.

**Comment by ghost** [comment]
Please if you rewrite this, rewrite it directly as an exe file like requested in my other thread
