### ISSUE TITLE
Updated it and got the same issue last time

### ISSUE THREAD

**Issue by 9HitCode** [phanirithvij/twist.moe#24]
$ ./startp.sh kono-yuusha-ga-ore-tueee-kuse-ni-shinchou-sugiru
URL: https://twist.moe/a/kono-yuusha-ga-ore-tueee-kuse-ni-shinchou-sugiru
making it https://twist.moe/a/kono-yuusha-ga-ore-tueee-kuse-ni-shinchou-sugiru/1
Fetching info...
rm: cannot remove '.temp.txt': No such file or directory
Traceback (most recent call last):
  File "../jsonP.py", line 5, in <module>
    sources = json.load(sys.stdin)
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "../decrypt.py", line 59, in <module>
    with open(file_name) as fn:
FileNotFoundError: [Errno 2] No such file or directory: '.temp.txt'
Creating kono-yuusha-ga-ore-tueee-kuse-ni-shinchou-sugiru/list.txt
copying download.sh to kono-yuusha-ga-ore-tueee-kuse-ni-shinchou-sugiru
Done
Check the Anime/kono-yuusha-ga-ore-tueee-kuse-ni-shinchou-sugiru folder
Enjoy
Done
downloads Added to animelist.txt
twist-batch-downloader.exe Added to animelist.txt

**Comment by phanirithvij** [comment]
Thanks for reporting. Download the twist.exe from the releases for now while I fix this.

**Comment by phanirithvij** [comment]
It's here https://github.com/phanirithvij/twist.moe/releases

**Comment by 9HitCode** [comment]
Hey dude, just wanted to say great work on this downloader. 
I've tried different kind of anime batch downloader and they don't work as efficiently as yours or they feel very clunky and doesn't download HD. So anyways I'm getting an ERROR 403:Forbidden when trying to download links from Twist.moe, they may have stopped third-party downloads. 

So it might not be the source code fault.  Anyways just wanted to give you a little compliment on the side.

**Comment by phanirithvij** [comment]
Thanks for reporting. I'm currently sick right now. I will get back to
making it work right after I recover.

**Comment by phanirithvij** [comment]
Hi, I checked it and it is working fine on my system.

```shell
D:\Projects\twist.moe (master -> origin)
λ bash startp.sh kono-yuusha-ga-ore-tueee-kuse-ni-shinchou-sugiru
URL: https://twist.moe/a/kono-yuusha-ga-ore-tueee-kuse-ni-shinchou-sugiru
Creating kono-yuusha-ga-ore-tueee-kuse-ni-shinchou-sugiru
making it https://twist.moe/a/kono-yuusha-ga-ore-tueee-kuse-ni-shinchou-sugiru/1
Fetching info...
https://twist.moe/anime/shinchouyuusha/%5BHorribleSubs%5D%20Shinchou%20Yuusha%20-%2001%20%5B1080p%5D.mp4
https://twist.moe/anime/shinchouyuusha/%5BHorribleSubs%5D%20Shinchou%20Yuusha%20-%2002%20%5B1080p%5D.mp4
https://twist.moe/anime/shinchouyuusha/%5BHorribleSubs%5D%20Shinchou%20Yuusha%20-%2003%20%5B1080p%5D.mp4
https://twist.moe/anime/shinchouyuusha/%5BHorribleSubs%5D%20Shinchou%20Yuusha%20-%2004%20%5B1080p%5D.mp4
https://twist.moe/anime/shinchouyuusha/%5BHorribleSubs%5D%20Shinchou%20Yuusha%20-%2005%20%5B1080p%5D.mp4
https://twist.moe/anime/shinchouyuusha/%5BHorribleSubs%5D%20Shinchou%20Yuusha%20-%2006%20%5B1080p%5D.mp4
https://twist.moe/anime/shinchouyuusha/%5BHorribleSubs%5D%20Shinchou%20Yuusha%20-%2007%20%5B1080p%5D.mp4
https://twist.moe/anime/shinchouyuusha/%5BHorribleSubs%5D%20Shinchou%20Yuusha%20-%2008%20%5B1080p%5D.mp4
https://twist.moe/anime/shinchouyuusha/%5BHorribleSubs%5D%20Shinchou%20Yuusha%20-%2009%20%5B1080p%5D.mp4
https://twist.moe/anime/shinchouyuusha/%5BHorribleSubs%5D%20Shinchou%20Yuusha%20-%2010%20%5B1080p%5D.mp4
https://twist.moe/anime/shinchouyuusha/%5BHorribleSubs%5D%20Shinchou%20Yuusha%20-%2011%20%5B1080p%5D.mp4
https://twist.moe/anime/shinchouyuusha/%5BHorribleSubs%5D%20Shinchou%20Yuusha%20-%2012%20%5B1080p%5D.mp4
Creating kono-yuusha-ga-ore-tueee-kuse-ni-shinchou-sugiru/list.txt
copying download.sh to kono-yuusha-ga-ore-tueee-kuse-ni-shinchou-sugiru
Done
Check the Anime/kono-yuusha-ga-ore-tueee-kuse-ni-shinchou-sugiru folder
Enjoy
kono-yuusha-ga-ore-tueee-kuse-ni-shinchou-sugiru Added to animelist.txt
```

**Comment by p-dimi** [comment]
I had the same error at first.
You need to have the requirements installed:
```
pycryptodomex # this is recommended and nothing else like pycrypto or Crypto or pycryptodome
hashlib
requests
```

I misread the requirements instructions originally and installed pycrypto. That was wrong.
Make sure you have exactly pycryptodomex.

Once I did that everything was fine.
Just make sure you have the right requirements installed and don't be a dummy like me & misread what the comment says.

**Comment by phanirithvij** [comment]
That must be it. Thanks for clarifying it @p-dimi I'll make sure to update the readme.

**Comment by 9HitCode** [comment]
Sorry for the really late reply, as for the requirements I already had them all downloaded but for some reason it stopped working. Anyways working perfectly now, might have been some errors from Twsit.moe side Thanks by the way!
