### ISSUE TITLE
Cat command missing "list.txt"

### ISSUE THREAD

**Issue by ulysseslc** [phanirithvij/twist.moe#25]
When I type ./download.sh twist.moe/Anime/kimetsu-no-yaiba into Cmder, it asks me to put in where I want to start downloading episodes from, and I put in the range, but at the end of the text it says "cat: list.txt: No such file or directory". 
![image](https://user-images.githubusercontent.com/64553077/80633910-90727800-8a27-11ea-8f6b-b3627c76f1f9.png)

**Comment by phanirithvij** [comment]
Can you do an `ls -l` in that directory and see if list.txt is there

**Comment by ulysseslc** [comment]
The only file in /Desktop/cmder/twist.moe/Anime/kimetsu-no-yaiba is download.sh
![image](https://user-images.githubusercontent.com/64553077/80733495-c3764380-8adb-11ea-9fbf-aff84c8d6fc7.png)

**Comment by ulysseslc** [comment]
The only file in that directory is download.sh
![image](https://user-images.githubusercontent.com/64553077/80733567-e274d580-8adb-11ea-8144-05591e2f0157.png)

**Comment by phanirithvij** [comment]
from the `twist.moe` directory run `./startp.sh kimetsu-no-yaiba` and show the output here.

**Comment by ulysseslc** [comment]
That generated a list.txt file for me and now I can run ./download.sh thank you! Is there a way I could possibly speed up the download speed because it starts downloading at my normal download speed but falls down to below a kilobyte sometimes

**Comment by phanirithvij** [comment]
Download speed depends on the twist.moe server and your internet connection. Nothing we can do.
