### ISSUE TITLE
How do I use it to search an anime directly?

### ISSUE THREAD

**Issue by DishankJ** [phanirithvij/twist.moe#28]

**Comment by phanirithvij** [comment]
Didn't implement tat feature because there's no search api from twist.moe. But there is however the anime project I mentioned in the readme which shows results from much more sites and also is active, it can also download from twist.moe. I suggest using it for the time being.

**Comment by phanirithvij** [comment]
TODO

- query anime list
- cache it
- search in the list
- if not found retry by querying again
- cache newly fetched
- if found cool else no such anime

also [fuzzysearch](https://github.com/seatgeek/fuzzywuzzy)

**Comment by phanirithvij** [comment]
Hey, implemented some part of it. you can try with `python allanimenew.py` then `python search.py <term>`
